### ISSUE TITLE
这行代码会导致切换回本月的时候，直接选中本月的第一天。而不是当天

### ISSUE THREAD

**Issue by RyanPan-SW** [CiroLee/vue-materials#1]
https://github.com/CiroLee/vue-materials/blob/084e4198c9e512d61328f631522771d93ee77a0c/src/components/calendar/index.vue#L85

**Comment by CiroLee** [comment]
这段代码是防止切换时跳月的现象(如8月31日切到九月，会直接跳到10月，因为9月没有31日，Date会自动寻找下一个符合条件的月份，所以这里需要指定一个都有的日期， 如1日)。
切换本月要显示当天，加一个条件判断即可，已修复。
